# Generated by Django 2.2.7 on 2020-07-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0049_auto_20200315_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.TextField()),
                ('instructor', models.CharField(max_length=40)),
            ],
        ),
    ]
