# Generated by Django 3.0.7 on 2020-07-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0050_assignments_submissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='title',
            new_name='stitle',
        ),
    ]
