# Generated by Django 2.2.7 on 2020-07-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0052_auto_20200729_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
