# Generated by Django 2.2.7 on 2020-07-30 10:16

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0054_tutorial_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
