# Generated by Django 3.0.7 on 2020-07-28 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0055_remove_assignments_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
