# Generated by Django 2.2.7 on 2020-07-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0056_auto_20200730_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='c',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second.Tutorial'),
        ),
    ]
