# Generated by Django 3.0.7 on 2020-07-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0058_auto_20200728_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='deadline',
            field=models.DateField(),
        ),
    ]
