# Generated by Django 2.2.7 on 2020-07-31 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0060_auto_20200730_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second.Course'),
        ),
    ]
