# Generated by Django 3.0.7 on 2020-07-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0060_assignments_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='author',
        ),
    ]
