# Generated by Django 2.2.7 on 2020-07-31 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0061_auto_20200731_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='course',
            new_name='course_title',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='course_title',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='course',
            new_name='course_title',
        ),
    ]
