# Generated by Django 3.0.7 on 2020-07-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0062_auto_20200728_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='file',
            field=models.FileField(null=True, upload_to='assignments/', verbose_name=''),
        ),
    ]
