# Generated by Django 2.2.7 on 2020-07-31 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0062_auto_20200731_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='course_title',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='course_title',
            new_name='subject',
        ),
    ]
