# Generated by Django 3.0.7 on 2020-07-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0068_grading'),
        ('second', '0050_course'),
    ]

    operations = [
    ]
