# Generated by Django 2.2.7 on 2020-08-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0068_grading'),
        ('second', '0066_auto_20200731_1953'),
    ]

    operations = [
    ]
