# Generated by Django 3.0.7 on 2020-08-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0068_grading'),
        ('second', '0055_auto_20200730_1601'),
    ]

    operations = [
    ]
