# Generated by Django 3.0.7 on 2020-08-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0069_merge_20200801_0624'),
        ('second', '0064_auto_20200731_1444'),
    ]

    operations = [
    ]
