# Generated by Django 3.0.8 on 2020-08-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0069_merge_20200801_1216'),
        ('second', '0069_merge_20200730_1246'),
    ]

    operations = [
    ]
