# Generated by Django 3.0.7 on 2020-08-08 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0070_merge_20200808_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='second.SID'),
            preserve_default=False,
        ),
    ]
