# Generated by Django 3.0.7 on 2020-08-08 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0071_grading_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='second.Assignments'),
            preserve_default=False,
        ),
    ]
