# Generated by Django 3.0.7 on 2020-08-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0072_grading_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grading',
            name='name',
        ),
    ]
