# Generated by Django 3.0.7 on 2020-08-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0073_remove_grading_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
