# Generated by Django 3.0.8 on 2020-08-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0073_remove_grading_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='File'),
        ),
    ]
