# Generated by Django 3.0.8 on 2020-08-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0074_auto_20200808_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['-date_posted']},
        ),
    ]
