# Generated by Django 3.0.7 on 2020-08-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0074_auto_20200808_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
