# Generated by Django 3.0.7 on 2020-08-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0075_auto_20200808_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='grading',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
