# Generated by Django 3.0.7 on 2020-08-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0077_auto_20200808_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
