# Generated by Django 3.0.7 on 2020-08-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0074_auto_20200808_2032'),
        ('second', '0080_remove_grading_description'),
    ]

    operations = [
    ]
