# Generated by Django 3.0.7 on 2020-08-16 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0075_auto_20200808_1958'),
        ('second', '0083_auto_20200808_1520'),
    ]

    operations = [
    ]
