# Generated by Django 3.0.7 on 2020-08-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0085_auto_20200821_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
