# Generated by Django 3.0.7 on 2020-08-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0086_delete_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Routine',
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-date_posted']},
        ),
    ]
