# Generated by Django 3.0.8 on 2020-08-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0090_auto_20200828_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
