# Generated by Django 3.0.8 on 2020-08-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0094_auto_20200830_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
