# Generated by Django 3.0.8 on 2020-09-12 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0096_auto_20200830_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='course',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
