# Generated by Django 3.0.8 on 2020-09-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0092_auto_20200912_1625'),
        ('second', '0097_auto_20200912_2012'),
    ]

    operations = [
    ]
