# Generated by Django 3.0.7 on 2020-09-20 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0092_auto_20200912_1625'),
        ('second', '0097_auto_20200912_2012'),
    ]

    operations = [
    ]
