# Generated by Django 3.0.8 on 2020-09-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0098_merge_20200925_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(null=True, upload_to='attachments/', verbose_name='File'),
        ),
    ]
