# Generated by Django 3.0.7 on 2020-09-29 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0098_merge_20200925_2136'),
        ('second', '0098_merge_20200920_0820'),
    ]

    operations = [
    ]
