# Generated by Django 3.0.8 on 2020-10-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0099_auto_20200929_1737'),
        ('second', '0100_assignments_course'),
    ]

    operations = [
    ]
