# Generated by Django 3.0.7 on 2020-10-01 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0101_merge_20201001_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
